### ISSUE TITLE
Microsoft Excel 不能使用对象链接和嵌入的错误

### ISSUE THREAD

**Issue by KAIXIE** [aswjh/excel#11]
Microsoft Excel 不能使用对象链接和嵌入的错误

**Comment by KAIXIE** [comment]
![image](https://user-images.githubusercontent.com/11786672/56110480-37a08080-5f87-11e9-8af7-f74159882f5e.png)

**Comment by aswjh** [comment]
是用的例子代码吗？
可能是系统的设置问题 ，网上搜索一下，有这个问题的解决方法
