### ISSUE TITLE
Reading cell formatted as "Currency"

### ISSUE THREAD

**Issue by gitdlam** [aswjh/excel#2]
Hi hope all is well.  
When i try to read a cell that is formatted as "Currency" i got nothing.

In the end i added this to the excel.String function (copied excel.String modfied the copy)

```
    case excel.VARIANT:

        if val.(excel.VARIANT).VT == ole.VT_CY {
            _val := *((*int64)(unsafe.Pointer(&val.(excel.VARIANT).Val)))
            ret = strconv.FormatFloat(float64(_val)*float64(0.0001), 'f', -1, 64)

        }
```

There is probably a better way of doing this. Just want to let you know.

**Comment by aswjh** [comment]
Updated, thanks.
