### ISSUE TITLE
How to do  sheet.UsedRange.Rows.Count like python?

### ISSUE THREAD

**Issue by dlintw** [aswjh/excel#5]
I want to get current Used Rows, is there any method?

**Comment by aswjh** [comment]
_cnt, _ := excel.GetProperty(sheet.Idisp, "UsedRange", "Rows", "Count")
cnt := _cnt.(int32)

**Comment by dlintw** [comment]
有機會封裝一個動態名稱的 method 嗎? 將類似這類的一網打盡.
也許是GetPropByOle("UsedRange.Rows.Count") 依據 "." 分割, 然後傳回 Varient

**Comment by aswjh** [comment]
用excel.GetProperty可以简化一点,上面改了一下

**Comment by dlintw** [comment]
謝謝, 建議加入 README.md

**Comment by aswjh** [comment]
现在可以使用sheet.MustGet("UsedRange", "Rows", "Count").(int32)
