### ISSUE TITLE
Disable Screen Update and stop Calculation in long update job

### ISSUE THREAD

**Issue by dlintw** [aswjh/excel#6]
I was use python to implement like, is there any method could do the same in golang?

```
Excel.ScreenUpdating = False
Excel.Calculation=-4135 # manual
.... long job
Excel.ScreenUpdating = True
Excel.Calculation=-4105 # auto
```

**Comment by aswjh** [comment]
在option里增加ScreenUpdating

**Comment by dlintw** [comment]
Is there readonly option? where to search available options?
I'm trying to google, but 'Visible' is not in the following page.
https://msdn.microsoft.com/en-us/library/office/ff194819.aspx

**Comment by dlintw** [comment]
Seems here https://msdn.microsoft.com/en-us/library/office/dn254068.aspx
maybe it is better to put this comment on the README.md's example code

**Comment by aswjh** [comment]
office的帮助比较详细,特别是有关vba编程的部分.
有些问题不清楚,可以在excel中实际操作,来录制vba宏,宏代码里面就可以看到写法了
