### ISSUE TITLE
Add example to show how to read an excel file.

### ISSUE THREAD

**Issue by zyfdegh** [aswjh/excel#7]
I am confused of using this lib to open a *.xls file, because it returns `@Open:` when I call the Open() func.

``` go
func process(file string) (err error) {
    option := excel.Option{"Visible": true, "DisplayAlerts": true}
    mso, err := excel.Open(file, option)
    if err != nil {
        log.Printf("open excel error: %v\n", err)
        return
    }
    fmt.Println(mso.Version)
    fmt.Println(mso.FILEFORMAT)
    return
}
```

Output is :

``` go
2016/10/09 09:51:15 open excel error: @Open:
```

So, any idea of adding some demo codes in **README.md** to show how to open an excel file?

**Comment by zyfdegh** [comment]
BTW, I ran above codes on Linux amd64.

**Comment by aswjh** [comment]
It depends on windows ole, works only on windows.

**Comment by zyfdegh** [comment]
Got it, it works now.
