### ISSUE TITLE
how can i read range values?

### ISSUE THREAD

**Issue by shamilsun** [aswjh/excel#9]
r := oleutil.MustGetProperty(sheet.Range("B3:D10").Idisp,"Value").ToArray()

	//println(r)
	//

	for ka, va := range r.ToValueArray() {
		fmt.Printf("key[%s] value[%s]\n", ka, va)
	}

got Nil values

**Comment by aswjh** [comment]
use sheet.GetRange("a1:b5") or sheet.MustGetRange("a1:b5")

**Comment by shamilsun** [comment]
can you print example with

sheet.GetRange("a1:b5") or sheet.MustGetRange("a1:b5")

do not see how to use this methods (have no iDispatch interface) for print values.

how to print values?

**Comment by aswjh** [comment]
here is an example:
 ``````
    sheet.PutRange("a3:c3", []string {"@1", "@2", "@3"})
    sheet.Range("d3:f3").Put([]string {"~4", "~5", "~6"})
    val := sheet.MustGetRange("a1:e5")
    if v, ok := val.([][]interface{}); ok {
        for i, row := range v {
            for j, x := range row {
                fmt.Println("xxx1", i, j, x)
                fmt.Println("xxx2", i, j, excel.String(x))
            }
        }
    } else if row, ok := val.([]interface{}); ok {
        for j, x := range row {
            fmt.Println("yyy", j, x)
        }
    }

``````

**Comment by shamilsun** [comment]
thank you

also , i found issue with "Visible":false , 

//runtime.GOMAXPROCS(1)
	option := excel.Option{"Visible":false,"DisplayAlerts": false,"ScreenUpdating": false}
	xl, _ := excel.OpenReadOnly(excelFileName,option) //xl, _ := excel.Open("test_excel.xls", option);

80% crushed
R:\projects\hello>go run hello.go
@Open: The server threw an exception.
goroutine 1 [running]:
runtime/debug.Stack(0x26, 0xc0420699e0, 0x41002f)
        R:/Go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
        R:/Go/src/runtime/debug/stack.go:16 +0x29
github.com/aswjh/excel.Except(0x522012, 0x4, 0xc042069df0, 0x0, 0x0, 0x0)
  

but with "Visible":true, its running fine.


i have already big experience with Excel OLE on delphi/pascal
on delphi was same issue, this named 'rejected by callee'

for fix it on delphi i did:

 LOleMsgFilter := IOleMessageFilter.Create;
 LOleMsgFilter.RegisterFilter;
    XLApp:= CreateOleObject(excelappname );  //need window interactive!!!
// here we got Excel Object with visible = true initial, but hidden on desktop
  LOleMsgFilter.RevokeFilter;
 FreeAndNil(LOleMsgFilter);

is it possible on golang (im new with go) ?


,

**Comment by aswjh** [comment]
I had never met this type of question,
Did you try runtime.GOMAXPROCS(1)?
